#!/usr/local/bin/bash

IP=$1
PLAYLIST_ID=$(cat /tmp/playlist_id)

if [ "$2" = album ]; then
read -p "Type Album Name Line: " ANS
SELECTION=$(head -$ANS /tmp/albums_position.txt | tail -1)
curl http://$IP:7814/api1/start/$PLAYLIST_ID/$SELECTION
fi

if [ "$2" = playlist ]; then
read -p "Type Playlist Name Line: " ANS
SELECTION=$(head -$ANS /tmp/playlists_id.txt | tail -1)
curl http://$IP:7814/api1/start/$SELECTION/0
fi

if [ "$2" = volume ]; then
read -p "Set Volume Value: " ANS
curl http://$IP:7814/api1/setvolume/$ANS
fi
