#!/bin/sh
#set opts

# add opts./replace commands
alias \
	..='cd ..' \
	...='cd ../..' \
	cp='cp -iv' \
	ls='exa -lag' \
	bat='bat -p' \
	du='BLOCKSIZE=1073741824 du -s * | sort -rnk 1' \
	wget='wget --hsts-file="$XDG_CONFIG_HOME"/wget-hsts' \
	gpg2='gpg2 --homedir "$XDG_DATA_HOME"/gnupg' \
	v='nvim' \
	d='devour' \
	xdotool_table='xmodmap -pk' \
	update="doas pkg_add -uvi" \
	cleanup="doas pkg_delete -a" \
	pkg_list="/bin/ls -1 /var/db/pkg" \
	"xdg-ninja"="~/.local/scripts/xdg-ninja/xdg-ninja.sh" \
	printfile='lp -d HP_Officejet_5740_series' \
	push='git add . && git commit && git push' \
	pull='git pull' \
	ssh_home='ssh "$(cat /opt/Sync/Arch\ IP)"' \
	ssh_vnc='ssh "$(cat /opt/Sync/Arch\ IP)" -L 5900:localhost:5900' \
	ssh_vnc_vm='ssh "$(cat /opt/Sync/Arch\ IP)" -L 5900:localhost:5920' \
	ssh_komga='ssh "$(cat /opt/Sync/Arch\ IP)" -L 8443:localhost:8443' \
	sed='gsed' \
