#!/bin/sh
#set opts

# add opts./replace commands
alias \
	..='cd ..' \
	...='cd ../..' \
	cp='cp -iv' \
	ls='exa -lagH --group-directories-first --smart-group' \
	bat='bat -p' \
	du='BLOCKSIZE=1073741824 du -s * | sort -rnk 1' \
	wget='wget --hsts-file="$XDG_CONFIG_HOME"/wget-hsts' \
	gpg2='gpg2 --homedir "$XDG_DATA_HOME"/gnupg' \
	v='nvim' \
	d='devour' \
	xdotool_table='xmodmap -pk' \
	cleanup="doas pkg_delete -a" \
	pkg_list="/bin/ls -1 /var/db/pkg" \
	"xdg-ninja"="~/.local/bin/xdg-ninja/xdg-ninja.sh" \
	printfile='lp -d HP_Officejet_5740_series' \
	push='git add . && git commit && git push' \
	pull='git pull' \
	sed='gsed' \
	clipboard='xclip -selection clipboard' \

update(){
	npm install http-server --prefix ./.local/share/npm/bin/ && rm -rf ~/.npm
	doas pkg_add -uvi
}

function wininfo {
xprop | awk '
	/^WM_CLASS/{sub(/.* =/, "instancia:"); sub(/,/, "\nclase:"); print}
	/^WM_NAME/{sub(/.* =/, "título:"); print}'
}
