#!/usr/local/bin/bash

cp /etc/login.conf /etc/login.conf.backup

# Especificamos los valores para los parámetros
new_datasize_cur="1024M"
new_datasize_max="1024M"
new_maxproc_cur="320"
new_maxproc_max="384"
new_openfiles_cur="131072"
new_openfiles_max="232878"

# Utilizamos sed para establecer los nuevos valores para el grupo staff
sed -i -e "/^staff:/,/^[a-zA-Z]+:\\$/ {
    s/\(:datasize-cur=\)[^:]*:/\1$new_datasize_cur:/g
    s/\(:datasize-max=\)[^:]*:/\1$new_datasize_max:/g
    s/\(:maxproc-cur=\)[^:]*:/\1$new_maxproc_cur:/g
    s/\(:maxproc-max=\)[^:]*:/\1$new_maxproc_max:/g
    s/\(:openfiles-cur=\)[^:]*:/\1$new_openfiles_cur:/g
    s/\(:openfiles-max=\)[^:]*:/\1$new_openfiles_max:/g
}" /etc/login.conf
