#!/bin/sh

git clone https://github.com/bleachbit/bleachbit.git ~/.local/src/bleachbit

cd ~/.local/src/bleachbit && make -C po local

sed -i 's|#!/usr/bin/python3|#!/usr/local/bin/python3|' bleachbit.py
