#!/bin/sh

find ~ -type d -exec chmod 700 {} \;
find ~ -type f \( -not -path "~/.dotfiles/scripts" -o -not -path "~/.local/bin" \) -exec chmod 600 {} \;

find ~/.local/bin/ -type f -exec chmod 700 {} \; &

find ~/.dotfiles/scripts/ -type f -exec chmod 700 {} \; && \
find ~/.dotfiles/scripts -type f \( -name "*.tar" -o -name "*.zip" \) -exec chmod 600 {} \; &

find ~/.cache/ -type f -exec chmod 700 {} \; && \
find ~/.cache/ -type f \( -name "*.txt" -o -name "thumb.*" -o -name "*.log" -o -name "*.json" -o -name "*.jpg" \) -exec chmod 600 {} \; &

# Multimedia
find ~/Music/ -type d -exec chmod 700 {} \; && \
find ~/Music/ -type f -name "*.mp3" -exec chmod 600 {} \; &
find ~/Videos -type f -exec chmod 400 {} \;
