#!/bin/sh

# Define nombres de archivos temporales
lock_original="/tmp/lock.png"
lock_center="/tmp/lock-center.png"

# Realiza una captura de pantalla
sleep 0.2; import -window root "$lock_original"

# Obtiene el brillo del centro de la captura de pantalla
brightness=$(convert /tmp/lock.png -colorspace hsb -resize 1x1 txt:- | awk '{print $4}' | awk -F ',' '{gsub(/[^0-9]/,"",$3); print substr($3,1,length($3)-4)}')

# Determina si se debe utilizar el icono de bloqueo oscuro
if [ "$brightness" -lt 80 ]; then
    lock_icon="lock.png"
else
    lock_icon="lock-dark.png"
fi

# Agrega desenfoque a la captura de pantalla
convert "$lock_original" -blur 0x5 "$lock_original" && \
# Agrega el icono de bloqueo a la captura de pantalla desenfocada
convert "$lock_original" "$HOME/.dotfiles/img/$lock_icon" -gravity center -composite -matte "$lock_original" && \
# Bloquea la pantalla
i3lock -eui "$lock_original"
