#!/usr/local/bin/bash

# Cerrar todas las notificaciones de Dunst
dunstctl close-all

# Obtener el estado actual del micrófono
mic_status=$(doas /usr/bin/mixerctl record.volume.mute | awk -F= '{print $2}')

# Cambiar el estado del micrófono
if [ "$mic_status" = "off" ]; then
    doas /usr/bin/mixerctl record.volume.mute=on
    notify_message="Microphone Unmuted"
else
    doas /usr/bin/mixerctl record.volume.mute=off
    notify_message="Microphone Muted"
fi

# Notificar el cambio de estado del micrófono
notify-send "$notify_message"
